AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - config/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/gman/importer.rb

Metrics/ClassLength:
  Exclude:
    - lib/gman/importer.rb
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AccessModifierDeclarations:
  Exclude:
    - lib/gman/identifier.rb
