#! /usr/bin/env ruby
# frozen_string_literal: true

#
# Add one or more domains to a given group, running the standard import checks
#
# Usage: script/add [GROUP] [DOMAIN(S)]

require './lib/gman/importer'

if ARGV.length < 2
  puts 'Usage: script/add [GROUP] [DOMAIN(S)]'
  exit 1
end

group = ARGV[0]
domains = ARGV.drop(1)

Gman.import(group => domains)
