#! /usr/bin/env ruby
# frozen_string_literal: true

#
# Alphabetizes entries in the domains.txt file
#
# usage: script/alphabetize

require_relative '../lib/gman'
require_relative '../lib/gman/importer'

current = Gman::DomainList.current
current.alphabetize
current.write
