#! /usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'
require 'open-uri'
require './lib/gman'
require './lib/gman/importer'

current = Gman::DomainList.current

puts 'Checking for duplicate domains in the domain list...'
puts "Current list contains #{current.count} domains..."

dupe = current.count - current.domains.uniq.count
puts "Found #{dupe} duplicate domains"
exit 0 if dupe.zero?

dupes = current.domains.select { |domain| current.domains.count(domain) > 1 }

puts 'Duplicate domains:'
puts dupes
exit 1
