#!/usr/bin/env ruby
# frozen_string_literal: true

# Given an array of domains, removes them from the list
# Example usage: script/prune foo.invalid, bar.invalid, foo.bar.invalid

require_relative '../lib/gman'
require_relative '../lib/gman/domain_list'

domains = ARGV
domains = domains.clone.map { |d| d.delete ',' }

list = File.open('./config/domains.txt').read
puts "Starting list: #{Gman::DomainList.current.count} domains"

domains.each do |domain|
  list.gsub!(/^#{Regexp.escape(domain)}$\n/, '')
end

File.write './config/domains.txt', list

puts "Ending list: #{Gman::DomainList.current.count} domains"
