#!/usr/bin/env ruby

# ! /usr/bin/env ruby
# frozen_string_literal: true

#
# Add one or more domains to a given group, running the standard import checks
#
# Usage: script/add [GROUP] [DOMAIN(S)]

require './lib/gman/importer'
require 'parallel'

importer = Gman::Importer.new({})
options = { skip_dupe: true, skip_resolve: false }
list_path = File.expand_path '../config/domains.txt', __dir__

# Registry suffixes (e.g., gouv.fr, fed.us) have no DNS records of their own
SKIP_GROUPS = ['non-us gov', 'non-us mil', 'US Federal'].freeze

importer.logger.info "Starting list: #{Gman::DomainList.current.count} domains"

Gman.list.to_h.to_a.shuffle.each do |group, domains|
  next if SKIP_GROUPS.include?(group)

  Parallel.each(domains, progress: 'Validating') do |domain|
    next if domain.start_with?('!')
    next if importer.valid_domain?(domain, options)

    importer.logger.warn "#{domain} is not valid, removing from list"
    list = File.read(list_path)
    list.gsub!(/^#{Regexp.escape(domain)}$\n/, '')
    File.write list_path, list
  end
end

importer.logger.info "Ending list: #{Gman::DomainList.current.count} domains"
