#!/bin/sh
#
# Vendors the full list of US .gov domains from https://github.com/GSA/data
# Usage: script/vendor-gov-list

# Vendor the last file in the dotgov-domains folder that ends in `-full.csv`
wget https://raw.githubusercontent.com/cisagov/dotgov-data/main/current-full.csv -O ./config/vendor/dotgovs.csv

