#! /usr/bin/env ruby
#
# Vendors the USA.gov-maintained list of US domains into domains.txt
# Source: https://github.com/GSA-OCSIT/govt-urls
#
# Usage: script/vendor-us
#
# Will automatically fetch latest version of the list and merge
# You can check for changes and commit via `git status`
#
# It's also probably a good idea to run `script/ci-build` for good measure

require './lib/gman/importer'

source = "https://raw.githubusercontent.com/GSA/govt-urls/master/government-urls.yaml"
blacklist = ["usagovQUASI"]

data = open(source).read
domains = YAML.load(data)
domains.reject! { |group,domain| blacklist.include?(group) }

Gman.import(domains)
