#! /usr/bin/env ruby
# frozen_string_literal: true

#
# Vendors the USA.gov-maintained list of US domains into domains.txt
# Source: https://github.com/GSA-OCSIT/govt-urls
#
# Usage: script/vendor-us
#
# Will automatically fetch latest version of the list and merge
# You can check for changes and commit via `git status`
#
# It's also probably a good idea to run `script/ci-build` for good measure

require './lib/gman'
require 'open-uri'
require 'csv'

path = File.expand_path('./vendor-us-tmp.csv')
blacklist = %w[usagovQUASI usagovFEDgov]
source = 'https://raw.githubusercontent.com/GSA/govt-urls/main/1_govt_urls_full.csv'
domains = {}

begin
  raw = URI.open(source).read
  File.write(path, raw)
  data = CSV.table(path)

  data.each do |domain|
    next if domain[:type_of_government] == 'Quasigovernmental'

    group = "US #{domain[:type_of_government]}"
    group += " (#{domain[:state]})" if domain[:type_of_government] != 'Federal' && domain[:state]
    domains[group] ||= []
    domains[group] << domain[:domain_name]
  end

  domains.reject! { |g, _| blacklist.include?(g) }
  Gman::Importer.new(domains).import
ensure
  File.delete(path)
end
