#! /usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'open-uri'
require './lib/gman'

url = 'https://raw.githubusercontent.com/robbi5/german-gov-domains/master/data/domains.csv'

domains = URI.open(url).read.encode('UTF-8')
domains = CSV.parse(domains, headers: true)
domains = domains.map { |row| row['Domain Name'] }

Gman::Importer.new('German Federal' => domains).import
