#!/bin/bash
#Runs all vendor scripts except script/vendor-nl

for file in script/vendor-*; do
  if [ "$file" != "script/vendor-nl" ]; then
    echo "*************************************"
    echo "Vendoring $file"
    echo "*************************************"
    "$file"
  fi
done

script/alphabetize
