#! /usr/bin/env ruby
# frozen_string_literal: true

require 'mechanize'
require 'csv'
require './lib/gman'

url = 'http://www.myndighetsregistret.scb.se/Myndighet.aspx'
agent = Mechanize.new
page = agent.get(url)
form = page.forms.first
form.radiobuttons.find { |r| r.value = 'Textfil' }.check
submit_button = form.buttons.find { |b| b.type == 'submit' }
response = agent.submit(form, submit_button)

rows = CSV.parse(response.content, headers: true, col_sep: "\t")
domains = rows.map do |row|
  row['Webbadress'] unless /UNIVERSITET/.match?(row['Namn'])
end

Gman::Importer.new('Swedish Administrative Authorities' => domains).import
