name: Clean domain list

on:
  push:
    branches: [main]

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby

        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Alphabetize
        run: bundle exec script/alphabetize

      - name: Dedupe
        run: bundle exec script/dedupe

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Clean domain list
            title: Clean domain list
            add-paths: config/*