name: "Validate Domain List"

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch: {}

jobs:
  validate: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby

        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Validate domains
        run: bundle exec script/validate-domains
 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: always()
        with:
            commit-message: Remove invalid domains
            title: Remove invalid domains
            add-paths: config/*